@startuml

cloud Exchange

:Trader UI: as TraderUI

package "Trading Engine" as TradingEngine {
  rectangle MarketAccess
  rectangle MarketData
  Rectangle Strategy
  
  MarketData -> Strategy
  Strategy <-> MarketAccess
  MarketAccess <-u-> Exchange
  MarketData <- Exchange
}

package "Data Publishers" as Publishers {
  rectangle ValuationPublishers
  rectangle MarketDataPublishers
}

package "Network Infrastructure" as NetworkInfrastructure {
  queue "\t\t\t\t\t\t\t\t\t\tNetworkMiddleware\t\t\t\t\t\t\t\t\t\t" as NetworkMiddleware
}

package "Data Application" as Database {
  rectangle "Instrument Service" as InstrumentService
  rectangle "Parameter Service" as ParameterService
  database "Database" as DB
  rectangle "Volatility Calculator" as VolCalc
  rectangle "Theo/Greeks Calculator" as TheoCalc
  rectangle "Other Calculators" as OtherCalc
  collections "GPUs"

  InstrumentService -d-> DB
  ParameterService -d-> DB
  TheoCalc -d-> GPUs
}

package "Middle Office" as MiddleOffice {
  database "Position Bridge"
  database "Trade Bridg"
  database "Spline Bridge"
  database "Portfolio Bridge"
}

cloud "Clearing Firms" as Clearing

Publishers -u-> TraderUI
Publishers -d-> NetworkMiddleware
TradingEngine <-d-> NetworkMiddleware
NetworkMiddleware <-d-> MiddleOffice
NetworkMiddleware <-d-> Database
MiddleOffice -l-> Clearing

@enduml